In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [23]:
df=pd.read_csv("machine.data",header=None)
df.head()

         0        1    2     3      4    5   6    7    8    9
0  adviser    32/60  125   256   6000  256  16  128  198  199
1   amdahl   470v/7   29  8000  32000   32   8   32  269  253
2   amdahl  470v/7a   29  8000  32000   32   8   32  220  253
3   amdahl  470v/7b   29  8000  32000   32   8   32  172  253
4   amdahl  470v/7c   29  8000  16000   32   8   16  132  132

In [25]:
df.shape

(209, 10)

In [ ]:
# df.rename({'0':'VendorName','1':'ModelName'},axis=1,inplace=True)

In [27]:
col_names=['VendorName','ModelName','MYCT','MMIN','MMAX','CACH','CHMIN','CHMAX','PRP','ERP']

In [28]:
df.columns=col_names

In [29]:
df.columns

Index(['VendorName', 'ModelName', 'MYCT', 'MMIN', 'MMAX', 'CACH', 'CHMIN',
       'CHMAX', 'PRP', 'ERP'],
      dtype='str')

In [48]:
df

    VendorName      ModelName  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  ERP
0      adviser          32/60   125   256   6000   256     16    128  198  199
1       amdahl         470v/7    29  8000  32000    32      8     32  269  253
2       amdahl        470v/7a    29  8000  32000    32      8     32  220  253
3       amdahl        470v/7b    29  8000  32000    32      8     32  172  253
4       amdahl        470v/7c    29  8000  16000    32      8     16  132  132
..         ...            ...   ...   ...    ...   ...    ...    ...  ...  ...
204     sperry           80/8   124  1000   8000     0      1      8   42   37
205     sperry  90/80-model-3    98  1000   8000    32      2      8   46   50
206     sratus             32   125  2000   8000     0      2     14   52   41
207       wang         vs-100   480   512   8000    32      0      0   67   47
208       wang          vs-90   480  1000   4000     0      0      0   45   25

[209 rows x 10 columns]

In [30]:
df.describe()

,MYCT,MMIN,MMAX,CACH,CHMIN,CHMAX,PRP,ERP
count,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000
mean,203.822967,2867.980861,11796.153110,25.205742,4.698565,18.267943,105.622010,99.330144
std,260.262926,3878.742758,11726.564377,40.628722,6.816274,25.997318,160.830733,154.757102
min,17.000000,64.000000,64.000000,0.000000,0.000000,0.000000,6.000000,15.000000
25%,50.000000,768.000000,4000.000000,0.000000,1.000000,5.000000,27.000000,28.000000
50%,110.000000,2000.000000,8000.000000,8.000000,2.000000,8.000000,50.000000,45.000000
75%,225.000000,4000.000000,16000.000000,32.000000,6.000000,24.000000,113.000000,101.000000
max,1500.000000,32000.000000,64000.000000,256.000000,52.000000,176.000000,1150.000000,1238.000000

In [31]:
# categorical=[col for col in df.columns if df[col].dtype='0']

In [32]:
# print(categorical)

In [33]:
df['VendorName'].unique()

<StringArray>
[     'adviser',       'amdahl',       'apollo',         'basf',
          'bti',    'burroughs',        'c.r.d',          'cdc',
       'cambex',          'dec',           'dg',    'formation',
   'four-phase',        'gould',           'hp',       'harris',
    'honeywell',          'ibm',          'ipl',     'magnuson',
    'microdata',          'nas',          'ncr',      'nixdorf',
 'perkin-elmer',        'prime',      'siemens',       'sperry',
       'sratus',         'wang']
Length: 30, dtype: str

In [34]:
df['ModelName'].unique()

<StringArray>
[        '32/60',        '470v/7',       '470v/7a',       '470v/7b',
       '470v/7c',        '470v/b',      '580-5840',      '580-5850',
      '580-5860',      '580-5880',
 ...
       '1100/94',          '80/3',          '80/4',          '80/5',
          '80/6',          '80/8', '90/80-model-3',            '32',
        'vs-100',         'vs-90']
Length: 209, dtype: str

In [35]:
df_cat=df.iloc[:,:2]
df_num=df.iloc[:,2:]

In [36]:
df_num.head()

   MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  ERP
0   125   256   6000   256     16    128  198  199
1    29  8000  32000    32      8     32  269  253
2    29  8000  32000    32      8     32  220  253
3    29  8000  32000    32      8     32  172  253
4    29  8000  16000    32      8     16  132  132

In [37]:
X=df_num.iloc[:,0:6]
y=df_num.iloc[:,-1]

In [38]:
y = y.values.reshape(-1, 1)

In [39]:
X.shape,y.shape

((209, 6), (209, 1))

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [41]:
X_train.shape,y_train.shape

((146, 6), (146, 1))

In [42]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.fit_transform(X_test)

In [43]:
model=LinearRegression()

In [44]:
model.fit(X_train,y_train)

LinearRegression()

In [45]:
y_pred=model.predict(X_test)

In [46]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [47]:
print("MSE: ", mse)
print("R2: ",r2)

MSE:  2366.8178233480976
R2:  0.8700195548230454